version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.env
  
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/library
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - web
      - db
    ports:
      - "80:80"
    volumes:
      - ./static/:/static
